{% set name = "full-fred" %}
{% set version = "0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/full_fred-{{ version }}.tar.gz
  sha256: aac80b6fc8753e8676efcffba1ec0bde5ed9f673ea50abc0086f341e62269c61

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=42
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - pandas
    - requests

test:
  imports:
    - full_fred
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/7astro7/full_fred
  summary: Full interface to Federal Reserve Economic Data (FRED)
  dev_url: https://github.com/7astro7/full_fred
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sumanth-manchala
